[[repos]]
repo = "local"

[[repos.hooks]]
id = "cargo-fmt"
name = "cargo fmt --check"
entry = "cargo fmt --all -- --check"
language = "system"
types = ["rust"]
pass_filenames = false

[[repos.hooks]]
id = "cargo-clippy"
name = "cargo clippy -D warnings"
entry = "cargo clippy --all-targets --all-features -- -D warnings"
language = "system"
types = ["rust"]
pass_filenames = false

[[repos.hooks]]
id = "typos"
name = "typos"
entry = "typos"
language = "system"
pass_filenames = false
